"""X.509 server credentials, verified against explicit root certificates.

Uses the crate's committed fixtures (`mls-tls/fixtures/`), generated by
`cargo run -p mls-tls --example generate_fixtures`. They are Ed25519, so every test here pins the
one suite that signs with Ed25519 rather than using the backend default.

This is the only end-to-end coverage of the X.509 config path anywhere in the repo — the Rust
`with_single_cert` builder has no other caller.
"""

from __future__ import annotations

import socket
import threading

import pytest

import mls_tls
from _helpers import ED25519_SUITE, FIXTURES, drive

pytestmark = pytest.mark.skipif(
    ED25519_SUITE not in mls_tls.SUPPORTED_CIPHER_SUITES,
    reason=f"the {mls_tls.BACKEND} backend does not serve the Ed25519 suite",
)

TIMEOUT = 10.0


@pytest.fixture(scope="module")
def fixtures():
    """The fixture CA, server certificate and raw server key, or skip if not generated."""
    needed = ["ca_cert.der", "server_cert.der", "server_secret_key.bin", "server_public_key.bin"]
    missing = [name for name in needed if not (FIXTURES / name).exists()]
    if missing:
        pytest.skip(
            f"missing {missing} — run `cargo run -p mls-tls --example generate_fixtures`"
        )
    return {name.split(".")[0]: (FIXTURES / name).read_bytes() for name in needed}


@pytest.fixture
def x509_server_config(fixtures):
    return mls_tls.ServerConfig(
        cert_chain=[fixtures["server_cert"]],
        private_key=fixtures["server_secret_key"],
        public_key=fixtures["server_public_key"],
        cipher_suite=ED25519_SUITE,
    )


def verifying_client(fixtures, **kwargs):
    return mls_tls.ClientConfig(
        basic_credential=b"client",
        root_certificates=[fixtures["ca_cert"]],
        cipher_suite=ED25519_SUITE,
        **kwargs,
    )


def test_public_key_is_derived_when_omitted(fixtures):
    """Supplying only the private key yields the same public key as the fixture records."""
    derived = mls_tls.derive_signature_public_key(
        ED25519_SUITE, fixtures["server_secret_key"]
    )
    assert derived == fixtures["server_public_key"]

    config = mls_tls.ServerConfig(
        cert_chain=[fixtures["server_cert"]],
        private_key=fixtures["server_secret_key"],
        cipher_suite=ED25519_SUITE,
    )
    assert config.public_key == fixtures["server_public_key"]


def test_chain_validates_against_the_ca(fixtures, x509_server_config):
    """The fixture certificate is issued for `localhost` and chains to the fixture CA."""
    client_config = verifying_client(fixtures)
    client = mls_tls.ClientConnection(client_config, "localhost")
    server = mls_tls.ServerConnection(x509_server_config)
    drive(client, server)

    assert not client.is_handshaking()
    assert client.getpeercert(binary_form=True) == fixtures["server_cert"]
    assert client.getpeercertchain() == [fixtures["server_cert"]]
    # An X.509 peer has no Basic identifier.
    assert client.peer_identity() is None


def test_wrong_hostname_is_rejected(fixtures, x509_server_config):
    """The certificate names `localhost`, so any other name must fail the directional check."""
    client_config = verifying_client(fixtures)
    client = mls_tls.ClientConnection(client_config, "wrong.example.com")
    server = mls_tls.ServerConnection(x509_server_config)

    with pytest.raises(mls_tls.CertificateError):
        drive(client, server)
    assert client.is_handshaking()


def test_unknown_ca_is_rejected(fixtures, x509_server_config):
    """A client trusting a different root must not accept the fixture chain."""
    client_config = mls_tls.ClientConfig(
        basic_credential=b"client",
        # The server's own leaf, used as a trust anchor: not the issuer, so path building fails.
        root_certificates=[fixtures["server_cert"]],
        cipher_suite=ED25519_SUITE,
    )
    client = mls_tls.ClientConnection(client_config, "localhost")
    server = mls_tls.ServerConnection(x509_server_config)

    with pytest.raises(mls_tls.CertificateError):
        drive(client, server)


def test_over_a_socket(fixtures, x509_server_config):
    """The same credential works through the socket wrapper, hostname check included."""
    errors: list = []
    listener = socket.socket()
    listener.bind(("127.0.0.1", 0))
    listener.listen(1)
    listener.settimeout(TIMEOUT)
    port = listener.getsockname()[1]

    def run():
        try:
            conn, _ = listener.accept()
            conn.settimeout(TIMEOUT)
            with x509_server_config.wrap_socket(conn) as tls:
                tls.sendall(b"secure: " + tls.recv(4096))
        except Exception as exc:  # noqa: BLE001
            errors.append(exc)
        finally:
            listener.close()

    thread = threading.Thread(target=run, daemon=True)
    thread.start()

    client_config = verifying_client(fixtures)
    sock = socket.create_connection(("127.0.0.1", port), timeout=TIMEOUT)
    with client_config.wrap_socket(sock, server_hostname="localhost") as tls:
        tls.sendall(b"hello")
        assert tls.recv(4096) == b"secure: hello"
        assert tls.getpeercert(binary_form=True) == fixtures["server_cert"]

    thread.join(TIMEOUT)
    if errors:
        raise errors[0]
