"""Type stubs for the compiled core. The public API is re-exported from ``mls_tls``."""

from typing import Sequence

BACKEND: str
DEFAULT_CIPHER_SUITE: int
SUPPORTED_CIPHER_SUITES: list[int]

MLS_128_DHKEMX25519_AES128GCM_SHA256_ED25519: int
MLS_128_DHKEMP256_AES128GCM_SHA256_P256: int
MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_ED25519: int
MLS_256_DHKEMX448_AES256GCM_SHA512_ED448: int
MLS_256_DHKEMP521_AES256GCM_SHA512_P521: int
MLS_256_DHKEMX448_CHACHA20POLY1305_SHA512_ED448: int
MLS_256_DHKEMP384_AES256GCM_SHA384_P384: int
MLS_256_XWING_AES256GCM_SHA512_P384: int

class MLSTLSError(Exception): ...
class WantReadError(MLSTLSError): ...
class WantWriteError(MLSTLSError): ...
class CertificateError(MLSTLSError): ...
class HandshakeError(MLSTLSError): ...
class UnsupportedError(MLSTLSError): ...
class RaggedEOF(MLSTLSError): ...

def generate_signature_key(cipher_suite: int) -> tuple[bytes, bytes]: ...
def derive_signature_public_key(cipher_suite: int, private_key: bytes) -> bytes: ...
def cipher_suite_name(cipher_suite: int) -> str | None: ...

class IoState:
    @property
    def tls_bytes_to_write(self) -> int: ...
    @property
    def plaintext_bytes_to_read(self) -> int: ...
    @property
    def peer_has_closed(self) -> bool: ...

class Session:
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> Session: ...

class ClientConfig:
    def __new__(
        cls,
        *,
        basic_credential: bytes | None = None,
        cert_chain: Sequence[bytes] | None = None,
        private_key: bytes | None = None,
        public_key: bytes | None = None,
        root_certificates: Sequence[bytes] | None = None,
        verify: bool = True,
        cipher_suite: int | None = None,
    ) -> ClientConfig: ...
    @property
    def cipher_suite(self) -> int: ...
    @property
    def public_key(self) -> bytes: ...

class ServerConfig:
    def __new__(
        cls,
        *,
        basic_credential: bytes | None = None,
        cert_chain: Sequence[bytes] | None = None,
        private_key: bytes | None = None,
        public_key: bytes | None = None,
        cipher_suite: int | None = None,
    ) -> ServerConfig: ...
    @property
    def cipher_suite(self) -> int: ...
    @property
    def public_key(self) -> bytes: ...

class _Connection:
    def read_tls(self, data: bytes) -> int: ...
    def process_new_packets(self) -> IoState: ...
    def write_tls_into(self, buf: bytearray | memoryview) -> int: ...
    def write_tls(self, max_size: int | None = None) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def read_into(self, buf: bytearray | memoryview) -> int: ...
    def read(self, size: int | None = None) -> bytes: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def is_handshaking(self) -> bool: ...
    def refresh_traffic_keys(self) -> None: ...
    def send_close_notify(self) -> None: ...
    def session(self) -> Session: ...
    def peer_identity(self) -> bytes | None: ...
    def getpeercert(self, binary_form: bool = False) -> bytes | None: ...
    def getpeercertchain(self) -> list[bytes] | None: ...
    def cipher(self) -> int | None: ...
    def epoch(self) -> int | None: ...

class ClientConnection(_Connection):
    def __new__(
        cls,
        config: ClientConfig,
        server_hostname: str,
        session: Session | None = None,
    ) -> ClientConnection: ...

class ServerConnection(_Connection):
    def __new__(cls, config: ServerConfig) -> ServerConnection: ...
